pipeline {
    agent any
    stages {
        stage('Build') {
            agent {
              docker { image 'node:14-alpine' }
            }
            steps {
                // show some magic of the container
                sh 'node --version'
                // stash some buildartefacts using "dist" as their qualifier
                // stash includes: 'playbook.yaml', name: 'dist'
            }
        }
        stage('Ansible') {
            agent any
            steps {
                // unstash some buildartefacts from a previous stage using "dist" as their qualifier
                // unstash 'dist'
                // show some ansible magic
                sh 'ansible --version'
                checkout scm
                dir("node-build") {
                    sh 'ansible-playbook -i /etc/ansible/inventory.yaml deployment/playbook.yaml'
                }
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}
